name = "hello-world"
license = "Apache-2.0"
version = "0.1.0"

[dependencies]
aiken-lang/stdlib = "1.8.0"

[dev-dependencies]

[[mint.scripts]]
when.title = "hello-world"
when.any = ["spend"]

[scripts.hello-world]
compiler = "aiken"
