name = "jimmyh-world/hello-world"
version = "0.1.0"
license = "Apache-2.0"
description = "A simple hello world example for Aiken"

[dependencies]
aiken-lang/stdlib = { version = "2.1.0", source = "github" }

[[repository]]
name = "aiken-lang/stdlib"
source = "github"
