name = "jimmyh-world/nft-one-shot"
version = "0.1.0"
license = "Apache-2.0"
plutus_version = "v2"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[migrations]]
name = "nft_policy"
path = "validators/nft_policy.ak"
