name = "jimmyh-world/escrow-contract"
version = "1.0.0"
license = "MIT"
plutus_version = "v2"
tests = true

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[[migrations]]
name = "escrow"
path = "validators/escrow.ak"
