name = "jimmyh-world/fungible-token"
version = "2.0.0"
license = "MIT"
plutus_version = "v2"
tests = true
description = "Production-grade fungible token with real admin signature verification"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"
